#!/bin/bash

if [ ! -d ~/.fzf/ ]; then
	echo "~/.fzf/ not found, cloning repo"
	git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
	~/.fzf/install --key-bindings --completion --no-update-rc > /dev/null
fi
