#!/bin/bash

# add simple apt-get or apt packages here

# apts
sudo apt install curl exa git zsh -y

# apt-gets
sudo apt-get install python3-pip ripgrep uidmap xclip -y

# for pyenv
sudo apt install zlib1g zlib1g-dev libssl-dev libbz2-dev libsqlite3-dev libncurses5-dev libreadline-dev libffi-dev lzma-dev python3-tk -y
# required for alacritty
sudo apt install cmake pkg-config libfreetype6-dev libfontconfig1-dev libxcb-xfixes0-dev libxkbcommon-dev python3 -y
