#!/bin/bash

cargo install alacritty --quiet

# We use Alacritty's default Linux config directory as our storage location here.
if [ ! -d ~/.config/alacritty/themes ] ; then
	echo "~/.config/alacritty/themes not found, cloning repo"
	git clone --depth=1 https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
fi
