#!/bin/bash

# create .fonts folder
mkdir -p ~/.fonts/Hack/

# download and install if missing
if [ -z "$(ls -A ~/.fonts/Hack/*.ttf 2>/dev/null)" ]; then
	# Hack nerd font
	curl -OL https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Hack.tar.xz

	# extract
	tar -xf Hack.tar.xz -C ~/.fonts/Hack/

	# refresh font cache, which references ~/.fonts/ automatically
	fc-cache -fv 2>&1 > /dev/null # Suppressing output but showing errors

	rm Hack.tar.xz
fi
