#!/bin/bash

# create .fonts folder
mkdir -p ~/.fonts/SourceCodePro/

# download and install if missing
if [ -z "$(ls -A ~/.fonts/SourceCodePro/*.ttf 2>/dev/null)" ]; then
	# SourceCodePro nerd font
	curl -OL https://github.com/ryanoasis/nerd-fonts/releases/latest/download/SourceCodePro.tar.xz

	# extract
	tar -xf SourceCodePro.tar.xz -C ~/.fonts/SourceCodePro/

	# refresh font cache, which references ~/.fonts/ automatically
	fc-cache -fv 2>&1 > /dev/null # Suppressing output but showing errors

	rm SourceCodePro.tar.xz
fi
